blunderbuss:
  # ExcludeApprovers controls whether approvers are considered to be
  # reviewers. By default, approvers are considered as reviewers if
  # insufficient reviewers are available. If ExcludeApprovers is true,
  # approvers will never be considered as reviewers.
  exclude_approvers: true

  # MaxReviewerCount is the maximum number of reviewers to request
  # reviews from. Defaults to 0 meaning no limit.
  max_request_count: 3

  # ReviewerCount is the minimum number of reviewers to request
  # reviews from. Defaults to requesting reviews from 2 reviewers
  request_count: 2

  # UseStatusAvailability controls whether blunderbuss will consider GitHub's
  # status availability when requesting reviews for users. This will use at one
  # additional token per successful reviewer (and potentially more depending on
  # how many busy reviewers it had to pass over).
  use_status_availability: false

config_updater:
  maps:
    configs/prow-dev/config/config.yaml:
      name: config
    configs/prow-dev/config/plugins.yaml:
      name: plugins
    configs/prow-dev/config/external_plugins_config.yaml:
      name: external-plugins-config
    configs/prow-dev/config/labels.yaml:
      name: labels-config
    configs/prow-dev/jobs/**/*.yaml:
      name: job-config
      gzip: true

size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520

require_matching_label:
  - missing_label: needs-type
    org: ti-community-infra
    repo: test-dev
    issues: true
    regexp: ^type/
    missing_comment: |
      There are no type labels on this issue. Please add an appropriate label by using one of the following commands:
      - `/type <type-name>`

triggers:
  - repos:
      - ti-community-infra/test-dev
    only_org_members: false

repo_milestone:
  ti-community-infra/test-dev:
    maintainers_id: 4300209
    maintainers_team: bots-maintainers
    maintainers_friendly_name: Robots Maintainers

milestone_applier:
  ti-community-infra/test-dev:
    master: v0.1.0

override:
  allow_top_level_owners: true

plugins:
  ti-community-infra/test-dev:
    plugins:
      - assign
      - blunderbuss
      - branchcleaner
      - size
      - welcome
      - wip
      - lifecycle
      - help
      - hold
      - milestone
      - milestoneapplier
      - trigger
      - override
  ti-community-infra/tichi:
    plugins:
      - config-updater

external_plugins:
  ti-community-infra/test-dev:
    - name: ti-community-lgtm
      events:
        - pull_request_review
        - pull_request
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request
    - name: ti-community-label
      events:
        - issue_comment
    - name: ti-community-autoresponder
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
        - pull_request
        - issues
    - name: needs-rebase
      events:
        - pull_request
        - issue_comment
    - name: ti-community-cherrypicker
      events:
        - pull_request
        - issue_comment
    - name: ti-community-label-blocker
      events:
        - pull_request
    - name: ti-community-contribution
      events:
        - pull_request
    - name: ti-community-tars
      events:
        - issue_comment
        - push
    - name: ti-community-format-checker
      events:
        - pull_request
        - issues
    - name: ti-community-issue-triage
      events:
        - pull_request
        - issues
        - issue_comment
    - name: ti-community-boss
      events:
        - pull_request
        - pull_request_review

