# yaml-language-server: $schema=https://docs.renovatebot.com/renovate-schema.json
extends:
  - config:base
  - group:recommended
  - :gitSignOff
# auto updating image in kubernetes files.
kubernetes: 
  fileMatch: 
    - configs/prow-dev/cluster/.+\\.(yaml|yml)$
packageRules:
  - matchPackagePatterns: [^ticommunityinfra/tichi-]
    matchManagers: kubernetes
    matchDatasources: [docker]
    groupName: "ticommunityinfra tichi images"
postUpdateOptions:
    # Run go mod tidy after Go module updates. 
    # This is implicitly enabled for major module updates when gomodUpdateImportPaths is enabled.
    - gomodTidy
    # Update source import paths on major module updates, using mod.
    - gomodUpdateImportPaths 
