linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - rowserrcheck
    - copyloopvar
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
