#  $schema: https://goreleaser.com/static/schema.json
archives:
  - id: bin
    format: binary
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: "ti-community-lgtm"
    binary: ticommunitylgtm
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitylgtm
    env:
      - CGO_ENABLED=0
  - id: "ti-community-merge"
    binary: ticommunitymerge
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitymerge
    env:
      - CGO_ENABLED=0
  - id: "ti-community-owners"
    binary: ticommunityowners
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityowners
    env:
      - CGO_ENABLED=0
  - id: "ti-community-label"
    binary: ticommunitylabel
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitylabel
    env:
      - CGO_ENABLED=0
  - id: "ti-community-tars"
    binary: ticommunitytars
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitytars
    env:
      - CGO_ENABLED=0
  - id: "ti-community-autoresponder"
    binary: ticommunityautoresponder
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityautoresponder
    env:
      - CGO_ENABLED=0
  - id: "ti-community-blunderbuss"
    binary: ticommunityblunderbuss
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityblunderbuss
    env:
      - CGO_ENABLED=0
  - id: "ti-community-label-blocker"
    binary: ticommunitylabelblocker
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitylabelblocker
    env:
      - CGO_ENABLED=0
  - id: "ti-community-contribution"
    binary: ticommunitycontribution
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitycontribution
    env:
      - CGO_ENABLED=0
  - id: "ti-community-cherrypicker"
    binary: ticommunitycherrypicker
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitycherrypicker
    env:
      - CGO_ENABLED=0
  - id: "check-external-plugin-config"
    binary: check-external-plugin-config
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/check-external-plugin-config
    env:
      - CGO_ENABLED=0
  - id: "rerere"
    binary: rerere
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/rerere
    env:
      - CGO_ENABLED=0
  - id: "ti-community-format-checker"
    binary: ticommunityformatchecker
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityformatchecker
    env:
      - CGO_ENABLED=0
  - id: "ti-community-issue-triage"
    binary: ticommunityissuetriage
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityissuetriage
    env:
      - CGO_ENABLED=0
source:
  enabled: true
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^config:"
release:
  github:
  prerelease: auto
dockers:
  - id: tichi-lgtm-plugin
    ids:
      - ti-community-lgtm
    image_templates:
      - "ticommunityinfra/tichi-lgtm-plugin:latest"
      - "ticommunityinfra/tichi-lgtm-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-lgtm-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/lgtm/Dockerfile
  - id: tichi-merge-plugin
    ids:
      - ti-community-merge
    image_templates:
      - "ticommunityinfra/tichi-merge-plugin:latest"
      - "ticommunityinfra/tichi-merge-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-merge-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/merge/Dockerfile
  - id: tichi-owners-plugin
    ids:
      - ti-community-owners
    image_templates:
      - "ticommunityinfra/tichi-owners-plugin:latest"
      - "ticommunityinfra/tichi-owners-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-owners-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/owners/Dockerfile
  - id: tichi-label-plugin
    ids:
      - ti-community-label
    image_templates:
      - "ticommunityinfra/tichi-label-plugin:latest"
      - "ticommunityinfra/tichi-label-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-label-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/label/Dockerfile
  - id: tichi-tars-plugin
    ids:
      - ti-community-tars
    image_templates:
      - "ticommunityinfra/tichi-tars-plugin:latest"
      - "ticommunityinfra/tichi-tars-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-tars-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/tars/Dockerfile
  - id: tichi-autoresponder-plugin
    ids:
      - ti-community-autoresponder
    image_templates:
      - "ticommunityinfra/tichi-autoresponder-plugin:latest"
      - "ticommunityinfra/tichi-autoresponder-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-autoresponder-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/autoresponder/Dockerfile
  - id: tichi-blunderbuss-plugin
    ids:
      - ti-community-blunderbuss
    image_templates:
      - "ticommunityinfra/tichi-blunderbuss-plugin:latest"
      - "ticommunityinfra/tichi-blunderbuss-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-blunderbuss-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/blunderbuss/Dockerfile
  - id: tichi-label-blocker-plugin
    ids:
      - ti-community-label-blocker
    image_templates:
      - "ticommunityinfra/tichi-label-blocker-plugin:latest"
      - "ticommunityinfra/tichi-label-blocker-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-label-blocker-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/labelblocker/Dockerfile
  - id: tichi-contribution-plugin
    ids:
      - ti-community-contribution
    image_templates:
      - "ticommunityinfra/tichi-contribution-plugin:latest"
      - "ticommunityinfra/tichi-contribution-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-contribution-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/contribution/Dockerfile
  - id: tichi-cherrypicker-plugin
    ids:
      - ti-community-cherrypicker
    image_templates:
      - "ticommunityinfra/tichi-cherrypicker-plugin:latest"
      - "ticommunityinfra/tichi-cherrypicker-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-cherrypicker-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/cherrypicker/Dockerfile
  - image_templates:
      - "ticommunityinfra/tichi-web:latest"
      - "ticommunityinfra/tichi-web:{{ .Tag }}"
      - "ticommunityinfra/tichi-web:{{ .Major }}"
    dockerfile: ./deployments/web/Dockerfile
    extra_files:
      - web/
  - id: tichi-check-external-plugin-config
    ids:
      - check-external-plugin-config
    image_templates:
      - "ticommunityinfra/tichi-check-external-plugin-config:latest"
      - "ticommunityinfra/tichi-check-external-plugin-config:{{ .Tag }}"
      - "ticommunityinfra/tichi-check-external-plugin-config:{{ .Major }}"
    dockerfile: ./deployments/utils/check-external-plugin-config/Dockerfile
  - id: rerere-component
    ids:
      - rerere
    image_templates:
      - "ticommunityinfra/rerere-component:latest"
      - "ticommunityinfra/rerere-component:{{ .Tag }}"
      - "ticommunityinfra/rerere-component:{{ .Major }}"
    dockerfile: ./deployments/components/rerere/Dockerfile
  - id: tichi-format-checker-plugin
    ids:
      - ti-community-format-checker
    image_templates:
      - "ticommunityinfra/tichi-format-checker-plugin:latest"
      - "ticommunityinfra/tichi-format-checker-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-format-checker-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/formatchecker/Dockerfile
  - id: tichi-issue-triage-plugin
    ids:
      - ti-community-issue-triage
    image_templates:
      - "ticommunityinfra/tichi-issue-triage-plugin:latest"
      - "ticommunityinfra/tichi-issue-triage-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-issue-triage-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/issuetriage/Dockerfile
