before:
  hooks:
    - go mod download
builds:
  -
    id: "ti-community-lgtm"
    binary: ticommunitylgtm
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitylgtm/main.go
    env:
      - CGO_ENABLED=0
  -
    id: "ti-community-merge"
    binary: ticommunitymerge
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitymerge/main.go
    env:
      - CGO_ENABLED=0
  -
    id: "ti-community-owners"
    binary: ticommunityowners
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityowners/main.go
    env:
      - CGO_ENABLED=0
  -
    id: "ti-community-label"
    binary: ticommunitylabel
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitylabel/main.go
    env:
      - CGO_ENABLED=0
  -
    id: "ti-community-tars"
    binary: ticommunitytars
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitytars/main.go
    env:
      - CGO_ENABLED=0
  - id: "ti-community-autoresponder"
    binary: ticommunityautoresponder
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityautoresponder/main.go
    env:
      - CGO_ENABLED=0
  - id: "ti-community-blunderbuss"
    binary: ticommunityblunderbuss
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunityblunderbuss/main.go
    env:
      - CGO_ENABLED=0
  - id: "ti-community-label-blocker"
    binary: ticommunitylabelblocker
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ticommunitylabelblocker/main.go
    env:
      - CGO_ENABLED=0
  - id: "rerere"
    binary: rerere
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/rerere/main.go
    env:
      - CGO_ENABLED=0
  - id: "check-external-plugin-config"
    binary: check-external-plugin-config
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/check-external-plugin-config/main.go
    env:
      - CGO_ENABLED=0
source:
  enabled: true
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^config:'
release:
  github:
  prerelease: auto
dockers:
  -
    binaries:
      - ticommunitylgtm
    builds:
      - ti-community-lgtm
    image_templates:
      - "ticommunityinfra/tichi-lgtm-plugin:latest"
      - "ticommunityinfra/tichi-lgtm-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-lgtm-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/lgtm/Dockerfile
  -
    binaries:
      - ticommunitymerge
    builds:
      - ti-community-merge
    image_templates:
      - "ticommunityinfra/tichi-merge-plugin:latest"
      - "ticommunityinfra/tichi-merge-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-merge-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/merge/Dockerfile
  -
    binaries:
      - ticommunityowners
    builds:
      - ti-community-owners
    image_templates:
      - "ticommunityinfra/tichi-owners-plugin:latest"
      - "ticommunityinfra/tichi-owners-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-owners-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/owners/Dockerfile
  -
    binaries:
      - ticommunitylabel
    builds:
      - ti-community-label
    image_templates:
      - "ticommunityinfra/tichi-label-plugin:latest"
      - "ticommunityinfra/tichi-label-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-label-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/label/Dockerfile
  -
    binaries:
      - ticommunitytars
    builds:
      - ti-community-tars
    image_templates:
      - "ticommunityinfra/tichi-tars-plugin:latest"
      - "ticommunityinfra/tichi-tars-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-tars-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/tars/Dockerfile
  -
    binaries:
      - ticommunityautoresponder
    builds:
      - ti-community-autoresponder
    image_templates:
      - "ticommunityinfra/tichi-autoresponder-plugin:latest"
      - "ticommunityinfra/tichi-autoresponder-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-autoresponder-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/autoresponder/Dockerfile
  -
    binaries:
      - ticommunityblunderbuss
    builds:
      - ti-community-blunderbuss
    image_templates:
      - "ticommunityinfra/tichi-blunderbuss-plugin:latest"
      - "ticommunityinfra/tichi-blunderbuss-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-blunderbuss-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/blunderbuss/Dockerfile
  -
    binaries:
      - ticommunitylabelblocker
    builds:
      - ti-community-label-blocker
    image_templates:
      - "ticommunityinfra/tichi-label-blocker-plugin:latest"
      - "ticommunityinfra/tichi-label-blocker-plugin:{{ .Tag }}"
      - "ticommunityinfra/tichi-label-blocker-plugin:{{ .Major }}"
    dockerfile: ./deployments/plugins/labelblocker/Dockerfile
  -
    binaries:
      - rerere
    builds:
      - rerere
    image_templates:
      - "ticommunityinfra/rerere-component:latest"
      - "ticommunityinfra/rerere-component:{{ .Tag }}"
      - "ticommunityinfra/rerere-component:{{ .Major }}"
    dockerfile: ./deployments/components/rerere/Dockerfile
  -
    image_templates:
      - "ticommunityinfra/tichi-web:latest"
      - "ticommunityinfra/tichi-web:{{ .Tag }}"
      - "ticommunityinfra/tichi-web:{{ .Major }}"
    dockerfile: ./deployments/web/Dockerfile
    extra_files:
      - web/
  -
    binaries:
      - check-external-plugin-config
    builds:
      - check-external-plugin-config
    image_templates:
      - "ticommunityinfra/tichi-check-external-plugin-config:latest"
      - "ticommunityinfra/tichi-check-external-plugin-config:{{ .Tag }}"
      - "ticommunityinfra/tichi-check-external-plugin-config:{{ .Major }}"
    dockerfile: ./deployments/plugins/check-external-plugin-config/Dockerfile