apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prow
  name: "prow-controller-manager"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: prow
  name: "prow-controller-manager"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - prow-controller-manager-leader-lock
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - get
  - update
  - list
  - watch
  - update
  - patch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: "prow-controller-manager"
rules:
- apiGroups:
   - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
  - watch
  - get
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: prow
  name: "prow-controller-manager"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-controller-manager"
subjects:
- kind: ServiceAccount
  name: "prow-controller-manager"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: "prow-controller-manager"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-controller-manager"
subjects:
- kind: ServiceAccount
  name: "prow-controller-manager"
  namespace: prow
