apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-operator
  name: jenkins-operator
  namespace: prow
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: jenkins-operator
  type: ClusterIP
