---
gitHubLogin: "ti-chi-bot"
gitHubToken: "/etc/github/token"
gitName: "ti-chi-bot"
gitEmail: "ti-community-prow-bot@tidb.io"
skipPullRequest: false
gitHubOrg: "ti-community-infra"
gitHubRepo: "tichi"
remoteName: "tichi"
includedConfigPaths:
  - "."
targetVersion: "latest"
prefixes:
  - name: "Prow"
    prefix: "gcr.io/k8s-prow/"
    repo: "https://github.com/kubernetes/test-infra"
    summarise: true
    consistentImages: true
