name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    tags:
      - v*
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.1
          args: --timeout=500s
